### ISSUE TITLE
TypeError: Cannot read property 'getFileName' of undefined

### ISSUE THREAD

**Issue by tamtakoe** [sindresorhus/caller-path#2] opened 2016-05-31 09:41 UTC
node 4.x

I have `/home/user/dev/project/client/jsx/__tests__/require-clean.js`

``` js
const callerPath = require('caller-path');

function requireClean(smthPath) {
    const calledFrom = callerPath();

    console.log(calledFrom);
    //...
}

module.exports = requireClean;
```

I use it in `/home/user/dev/project/client/jsx/applications/edit/__tests__/application.action.test.js`

``` js
const requireClean = require('../../../__tests__/require-clean');

describe('Some tests: ', () => {
    beforeEach(function () {
        requireClean('../../../smth');
    });
    //...
});
```

I must get in console:

```
/home/user/dev/project/client/jsx/applications/edit/__tests__/application.action.test.js
```

but I get the error:

```
TypeError: Cannot read property 'getFileName' of undefined
```

See [caller module](https://www.npmjs.com/package/caller). It works correct in the same situation

**Comment by kevva** [comment] 2016-06-01 19:04
Duplicate of #1.

**Closed as completed by kevva** 2016-06-01 19:04 UTC
